# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: nginx
  state_top:
    base:
      "*":
        - nginx
  pillars:
    top.sls:
      base:
        "*":
          - nginx

platforms:
  - name: bento/debian-8

suites:
  - name: default
    provisioner:
      pillars:
        nginx.sls:
          nginx:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        nginx.sls: pillar-custom.sls
